//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MESSAGES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MESSAGES() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MESSAGES", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos..
        /// </summary>
        internal static string ERR_LOGIN {
            get {
                return ResourceManager.GetString("ERR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string TXT_ADVERTENCIA {
            get {
                return ResourceManager.GetString("TXT_ADVERTENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor.! Complete todos los campos con (*).
        /// </summary>
        internal static string TXT_ADVERTENCIA_MSJ {
            get {
                return ResourceManager.GetString("TXT_ADVERTENCIA_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Andenes.
        /// </summary>
        internal static string TXT_ANDENES {
            get {
                return ResourceManager.GetString("TXT_ANDENES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Asistentes.
        /// </summary>
        internal static string TXT_ASISTENTES {
            get {
                return ResourceManager.GetString("TXT_ASISTENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistentes.
        /// </summary>
        internal static string TXT_ASSISTANTS {
            get {
                return ResourceManager.GetString("TXT_ASSISTANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías.
        /// </summary>
        internal static string TXT_CATEGORIAS {
            get {
                return ResourceManager.GetString("TXT_CATEGORIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Tipo de Comprobante.
        /// </summary>
        internal static string TXT_CMB_TIPO_COMPROBANTE {
            get {
                return ResourceManager.GetString("TXT_CMB_TIPO_COMPROBANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corte de Caja.
        /// </summary>
        internal static string TXT_CORTE_CAJA {
            get {
                return ResourceManager.GetString("TXT_CORTE_CAJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string TXT_CREATE {
            get {
                return ResourceManager.GetString("TXT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros.
        /// </summary>
        internal static string TXT_DATA {
            get {
                return ResourceManager.GetString("TXT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de Caja.
        /// </summary>
        internal static string TXT_DATOS_CORTE {
            get {
                return ResourceManager.GetString("TXT_DATOS_CORTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destinos por Rutas.
        /// </summary>
        internal static string TXT_DETALLE_RUTA {
            get {
                return ResourceManager.GetString("TXT_DETALLE_RUTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Directorios.
        /// </summary>
        internal static string TXT_DIRECTORIO {
            get {
                return ResourceManager.GetString("TXT_DIRECTORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choferes.
        /// </summary>
        internal static string TXT_DRIVERS {
            get {
                return ResourceManager.GetString("TXT_DRIVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Establecimientos.
        /// </summary>
        internal static string TXT_ESTABLECIMIENTOS {
            get {
                return ResourceManager.GetString("TXT_ESTABLECIMIENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidó su contraseña?.
        /// </summary>
        internal static string TXT_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("TXT_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horarios.
        /// </summary>
        internal static string TXT_HORARIOS {
            get {
                return ResourceManager.GetString("TXT_HORARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresoras.
        /// </summary>
        internal static string TXT_IMPRESORAS {
            get {
                return ResourceManager.GetString("TXT_IMPRESORAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string TXT_LOGIN {
            get {
                return ResourceManager.GetString("TXT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca de Vehículos.
        /// </summary>
        internal static string TXT_MARCA_VEHICULO {
            get {
                return ResourceManager.GetString("TXT_MARCA_VEHICULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo de Vehículos.
        /// </summary>
        internal static string TXT_MODELO_VEHICULO {
            get {
                return ResourceManager.GetString("TXT_MODELO_VEHICULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro eliminado correctamente.
        /// </summary>
        internal static string TXT_MSJ_BODY_EXITO_DELETE {
            get {
                return ResourceManager.GetString("TXT_MSJ_BODY_EXITO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro ingresado correctamente.
        /// </summary>
        internal static string TXT_MSJ_BODY_EXITO_INSERT {
            get {
                return ResourceManager.GetString("TXT_MSJ_BODY_EXITO_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo enviado correctamente.
        /// </summary>
        internal static string TXT_MSJ_BODY_EXITO_MAIL {
            get {
                return ResourceManager.GetString("TXT_MSJ_BODY_EXITO_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML firmado correctamente.
        /// </summary>
        internal static string TXT_MSJ_BODY_EXITO_SIGN_XML {
            get {
                return ResourceManager.GetString("TXT_MSJ_BODY_EXITO_SIGN_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro actualizado correctamente.
        /// </summary>
        internal static string TXT_MSJ_BODY_EXITO_UPDATE {
            get {
                return ResourceManager.GetString("TXT_MSJ_BODY_EXITO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML generado correctamente.
        /// </summary>
        internal static string TXT_MSJ_BODY_EXITO_XML {
            get {
                return ResourceManager.GetString("TXT_MSJ_BODY_EXITO_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.!.
        /// </summary>
        internal static string TXT_MSJ_TITULO_EXITO {
            get {
                return ResourceManager.GetString("TXT_MSJ_TITULO_EXITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPRESS ATENAS S.A..
        /// </summary>
        internal static string TXT_NAME_COMPANY {
            get {
                return ResourceManager.GetString("TXT_NAME_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Disco.
        /// </summary>
        internal static string TXT_NUMERO_DISCO {
            get {
                return ResourceManager.GetString("TXT_NUMERO_DISCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Oficinistas.
        /// </summary>
        internal static string TXT_OFICINISTAS {
            get {
                return ResourceManager.GetString("TXT_OFICINISTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos Administrativos.
        /// </summary>
        internal static string TXT_PAGOS_ADMINISTRATIVOS {
            get {
                return ResourceManager.GetString("TXT_PAGOS_ADMINISTRATIVOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos Pendientes.
        /// </summary>
        internal static string TXT_PAGOS_PENDIENTES {
            get {
                return ResourceManager.GetString("TXT_PAGOS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros Generales.
        /// </summary>
        internal static string TXT_PARAMETROS {
            get {
                return ResourceManager.GetString("TXT_PARAMETROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros por Terminal.
        /// </summary>
        internal static string TXT_PARAMETROS_LOCALIDAD {
            get {
                return ResourceManager.GetString("TXT_PARAMETROS_LOCALIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string TXT_PASS {
            get {
                return ResourceManager.GetString("TXT_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene permisos para acceder a la aplicación.
        /// </summary>
        internal static string TXT_PERMISOS {
            get {
                return ResourceManager.GetString("TXT_PERMISOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precios.
        /// </summary>
        internal static string TXT_PRECIOS {
            get {
                return ResourceManager.GetString("TXT_PRECIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Propietario de Vehiculos.
        /// </summary>
        internal static string TXT_PROPIETARIO_VEHICULO {
            get {
                return ResourceManager.GetString("TXT_PROPIETARIO_VEHICULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pueblos Destinos.
        /// </summary>
        internal static string TXT_PUEBLOS {
            get {
                return ResourceManager.GetString("TXT_PUEBLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordar.
        /// </summary>
        internal static string TXT_REMEMBER_ME {
            get {
                return ResourceManager.GetString("TXT_REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Cobro de Retenciones.
        /// </summary>
        internal static string TXT_RETENCIONES {
            get {
                return ResourceManager.GetString("TXT_RETENCIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Rutas.
        /// </summary>
        internal static string TXT_RUTA {
            get {
                return ResourceManager.GetString("TXT_RUTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucursales.
        /// </summary>
        internal static string TXT_SUCURSAL {
            get {
                return ResourceManager.GetString("TXT_SUCURSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasas de Usuario.
        /// </summary>
        internal static string TXT_TASAS_USUARIO {
            get {
                return ResourceManager.GetString("TXT_TASAS_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasas de Usuario no Sincronizadas.
        /// </summary>
        internal static string TXT_TASA_NO_ENVIADA {
            get {
                return ResourceManager.GetString("TXT_TASA_NO_ENVIADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminal.
        /// </summary>
        internal static string TXT_TERMINAL {
            get {
                return ResourceManager.GetString("TXT_TERMINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Asientos.
        /// </summary>
        internal static string TXT_TIPO_ASIENTO {
            get {
                return ResourceManager.GetString("TXT_TIPO_ASIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Tipo de Comprobantes.
        /// </summary>
        internal static string TXT_TIPO_COMPROBANTES {
            get {
                return ResourceManager.GetString("TXT_TIPO_COMPROBANTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Vehículos.
        /// </summary>
        internal static string TXT_TIPO_VEHICULO {
            get {
                return ResourceManager.GetString("TXT_TIPO_VEHICULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Viajes.
        /// </summary>
        internal static string TXT_TIPO_VIAJE {
            get {
                return ResourceManager.GetString("TXT_TIPO_VIAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Tokens.
        /// </summary>
        internal static string TXT_TOKENS {
            get {
                return ResourceManager.GetString("TXT_TOKENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string TXT_USER {
            get {
                return ResourceManager.GetString("TXT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boletos Vendidos.
        /// </summary>
        internal static string TXT_VENDIDOS {
            get {
                return ResourceManager.GetString("TXT_VENDIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Viajes.
        /// </summary>
        internal static string TXT_VIAJES {
            get {
                return ResourceManager.GetString("TXT_VIAJES", resourceCulture);
            }
        }
    }
}
